//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWash.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ManageContactDetails
    {
        public int mid { get; set; }
        public string mopeninghours { get; set; }
        public string mnumber { get; set; }
        public string memail { get; set; }
        public string maddress { get; set; }
    }
}
