//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWash.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_services
    {
        public int sid { get; set; }
        public string sname { get; set; }
    }
}
