//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWash.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TeamMemberDetails
    {
        public int TMid { get; set; }
        public string TMname { get; set; }
        public string TMprofession { get; set; }
        public string TMphoto { get; set; }
    }
}
