//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWash.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contact1
    {
        public int cid1 { get; set; }
        public string cname1 { get; set; }
        public string cemail1 { get; set; }
        public string csubject1 { get; set; }
        public string cmessage1 { get; set; }
    }
}
