//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWash.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer_Plan_Request
    {
        public int CPid { get; set; }
        public string CPname { get; set; }
        public string CPplan { get; set; }
        public string CPprice { get; set; }
        public string CPservices { get; set; }
    }
}
