//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWash.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SliderDetails
    {
        public int SLid { get; set; }
        public string SLsubject { get; set; }
        public string SLsubsubject { get; set; }
        public string SLdescription { get; set; }
        public string SLphoto { get; set; }
    }
}
