//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWash.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WashingPointDetails
    {
        public int WPid { get; set; }
        public string WPsubject { get; set; }
        public string WPsubsubject { get; set; }
        public string WPaddress { get; set; }
        public string WPnumber { get; set; }
    }
}
